---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: debian13-${BUILD_NUMBER}-${JOB_NAME}-${PLAYBOOK_VAR}
    region: us-west-1
    image: ami-071175b60c818694f
    vpc_subnet_id: subnet-04a8ad1b1d4da874c
    instance_type: t2.large
    ssh_user: admin
    root_device_name: /dev/xvda
    instance_tags:
      iit-billing-tag: toolkit-package-testing
      job-name: ${JOB_NAME}
provisioner:
  name: ansible
  log: True
  env:
    GLIBC: "2.35"
  playbooks:
    create: ../../playbooks/create.yml
    destroy: ../../playbooks/destroy.yml
    prepare: ../../playbooks/prepare.yml
    converge: ../../../playbooks/${PLAYBOOK_VAR}.yml
scenario:
  name: debian-13
  destroy_sequence:
    - destroy
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - destroy
